Updating required neutron version
build-openstack-sphinx-docs gate was raising an error and -1 on the
gate, due to neutron out of date version (12.0.0). This patch brings
neutron from the out-of-date version to the newest version
13.0.0.0b1.

Error logs:
   ubuntu-xenial |     'router': constants.L3,
   ubuntu-xenial | AttributeError: 'module' object has no attribute 'L3'

Please see more error logs in the following link
http://logs.openstack.org/04/557904/8/check/build-openstack-sphinx-docs/7a6b1da/job-output.txt.gz#_2018-07-03_04_00_47_083795

Change-Id: I1fbf47036b0fa2679aeb078a30d31fc771f614cf